### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._C'

### ISSUE THREAD

**Issue by chenzhao-CZ** [ryanemenecker/dodo#2] opened 2023-12-11 03:08 UTC
I was trying to run build.pdb_from_pdb using a local AF2 pdb and got the following message:

Predicting folded reigons, loops, and IDRs using AF2 structure information.
Building new structure.
{'idr_1': [0, 38], 'folded_2': [38, 583], 'idr_3': [583, 648], 'folded_4': [648, 800], 'idr_5': [800, 922]}
Setting position of folded domains
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chenzhao/.local/lib/python3.9/site-packages/dodo/build.py", line 252, in pdb_from_pdb
    PDBParserObj = build_structure(PDBParserObj, mode=mode,
  File "/home/chenzhao/.local/lib/python3.9/site-packages/dodo/idr_constructor.py", line 1376, in build_structure
    PDBParserObj=place_FDs(PDBParserObj,mode=mode, linear_placement=linear_placement,
  File "/home/chenzhao/.local/lib/python3.9/site-packages/dodo/idr_constructor.py", line 923, in place_FDs
    objective_dist = predict_e2e(PDBParserObj.sequence[domain1_coords_ind[-1]: domain2_coords_ind[0]])
  File "/home/chenzhao/.local/lib/python3.9/site-packages/dodo/idr_constructor.py", line 509, in predict_e2e
    return pr(sequence).predictor.end_to_end_distance()
  File "/home/chenzhao/.local/lib/python3.9/site-packages/sparrow/predictors/__init__.py", line 1165, in end_to_end_distance
    from .scaled_re.scaled_end_to_end_distance_predictor import ScaledRePredictor
  File "/home/chenzhao/.local/lib/python3.9/site-packages/sparrow/predictors/scaled_re/scaled_end_to_end_distance_predictor.py", line 1, in <module>
    from parrot import brnn_architecture
  File "/home/chenzhao/.local/lib/python3.9/site-packages/parrot/__init__.py", line 8, in <module>
    from .process_input_data import *
  File "/home/chenzhao/.local/lib/python3.9/site-packages/parrot/process_input_data.py", line 19, in <module>
    import torch.nn as nn
  File "/home/chenzhao/.local/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/home/chenzhao/.local/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 1, in <module>
    from .module import Module
  File "/home/chenzhao/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 8, in <module>
    from ..parameter import Parameter
  File "/home/chenzhao/.local/lib/python3.9/site-packages/torch/nn/parameter.py", line 2, in <module>
    from torch._C import _disabled_torch_function_impl
ModuleNotFoundError: No module named 'torch._C'

Thank you!

**Comment by ryanemenecker** [comment] 2023-12-11 20:07
Hi chenzhao-CZ,

After looking around, it looks like it's an install problem on your end as far as torch (see: https://github.com/nmilosev/pytorch-arm-builds/commit/8c811255de7d7e52268b204c7746bfb2be2e6893#diff-a39b761a102da294c8a6a0d8411efd20f0bde7dc8b568d38580d3899ca54498b). However, without more information it'll be hard for me to help. Nonetheless, there are a few things you could try out:

1. Upgrade torch to see if  it's a bug in an old version of torch that has since been fixed. Run: `pip install torch --upgrade` from terminal to upgrade torch.
2. Reinstall DODO. I did have some dependency issues a while back, and I think one of them had to do with Torch. I fixed that bug, but depending on when you installed DODO you might still have it. Run: `pip install git+https://github.com/ryanemenecker/dodo.git` to reinstall DODO. 

Sorry I can't be much more helpful. Dependency bugs can be a trick to fix. If you're using conda, one good test would be to startup a new virtual environment and then follow the DODO install instructions and install DODO in a clean environment. If you still have the problem at this point, if you could tell me the name of the structure you're trying to build, I could try to reproduce the bug on my end. 

Best,
ryanemenecker

**Comment by ryanemenecker** [comment] 2023-12-13 16:32
Hi chenzhao-CZ,

I'm going to close this issue because it doesn't seem to be specific to DODO from what I can tell and instead seems to be specific to your torch install. Feel free to reach out again if you are having troubles getting it to work.

Bestm
ryanemenecker

**Closed as completed by ryanemenecker** 2023-12-13 16:32 UTC
